### PR TITLE
Switch to makem and github actions

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi Damien,

I'm replying here to the email you sent where you linked this.  Feel free to tag me with @alphapapa if you need my attention on GitHub.

By default, `makem.sh` uses your local Emacs configuration's packages, so e.g. it would load dependencies from `~/.emacs.d/elpa`.  That is useful sometimes, but it's not the best way to lint and test code, because, of course, it depends on your personal configuration.

That's what the sandbox features are for.  There are two ways to use the sandbox features:

1.  In temporary sandboxes.  For example: `./makem.sh --sandbox lint`.  That will make a temporary sandbox directory, install the necessary dependencies and linters, run them, and then delete the temporary sandbox directory.  This ensures that your personal config does not affect the output, and it always uses the latest versions of the linters and dependencies that are installed from ELPA and MELPA (e.g. the linters `package-lint` and `relint`; linters that are included with Emacs, like `checkdoc`, are used from your system's Emacs installation).

2.  In non-temporary sandboxes.  For example, `./makem.sh --sandbox=.sandbox --install-deps --install-linters` creates a new sandbox directory named `.sandbox`, installs the package's current dependencies and the linters, and then returns.  Then you can run rules in that sandbox like `./makem.sh -s.sandbox lint` (using the short option form).  This avoids having to install dependencies every time.  Note as well that Emacs version-specific sandboxes are created, so e.g. since I'm using Emacs 26.3, it would make a `.sandbox/26.3` directory; if I later ran a snapshot version, it would make a `.sandbox/27.0.50` directory (and I would need to use `--install-deps --install-linters` the first time I used that sandbox directory).

You can also use the Makefile to run these rules, like `make sandbox=.sandbox install-deps=t install-linters=t lint` if you prefer that syntax.

Does that clear it up?  I was hoping the `--help`/usage instructions for the script would cover this well enough, but I should probably explain more of this in the documentation.  What do you think?

Thanks.

**Comment by alphapapa** [comment]
By the way, the `makem.sh` repo includes a GitHub Actions `test.yml` file that you should generally be able to use as-is.  If your package has more specific requirements, you should be able to add to it.

**Comment by DamienCassou** [comment]
@alphapapa:

> By default, makem.sh uses your local Emacs configuration's packages, so e.g. it would load dependencies from ~/.emacs.d/elpa. That is useful sometimes, but it's not the best way to lint and test code, because, of course, it depends on your personal configuration. That's what the sandbox features are for. There are two ways to use the sandbox features: [...]

This makes a lot of sense, thank you. I think the README would gain from containing exactly this information. I think it currently lacks a bit high-level information.

As you can see from the build result, there is still a failure when running with Emacs 25.3: it complains that Emacs 26.1 is missing. Do you know what is happening?

**Comment by alphapapa** [comment]
> As you can see from the build result, there is still a failure when running with Emacs 25.3: it complains that Emacs 26.1 is missing. Do you know what is happening?

I'm guessing that one of the linters requires Emacs 26.1 now.  You could disable linting in the `test.yml` file, or allow it to pass without causing CI failures (see comment in the file).

**Pull request merged**
